[package]
name = "streaming_concurrent_workflow"
description = "An example of a streaming concurrent workflow"
repository = "https://github.com/gterzian/rust_five_easy_pieces"
version = "0.0.0"
authors = ["Gregory Terzian"]
license = "MPL-2.0"

[dependencies]
crossbeam-channel = "0.4"
rayon = "1"